// icons

const icons = {
  backImage: require('../assets/icons/backImage/backImage.png'),
  locationBlack: require('../assets/icons/locationBlack/locationBlack.png'),
  locationSearch: require('../assets/icons/locationSearch/locationSearch.png'),
  warning: require('../assets/icons/warning/warning.png'),
  currentLocation: require('../assets/icons/currentLocation/currentLocation.png'),
  currentLocationWhite: require('../assets/icons/currentLocationWhite/currentLocationMap.png'),
  location: require('../assets/icons/location/location.png'),
  locationFilter: require('../assets/icons/locationFilter/locationFilter.png'),
  filterRadius: require('../assets/icons/filterRadius/filterRadius.png'),
  locationPin: require('../assets/icons/locationPin/locationPin.png'),
  pickLocation: require('../assets/icons/pickLocation/pickLocation.png'),
  notificationBell: require('../assets/icons/notificationBell/notificationBell.png'),
  filterIcon: require('../assets/icons/filterIcon/filterIcon.png'),
  cartBorder: require('../assets/icons/cartBorder/cartBorder.png'),
  deliveryIcon: require('../assets/icons/deliveryIcon/deliveryIcon.png'),
  cartFilled: require('../assets/icons/cartFilled/cartFilled.png'),
  cartGreenCircle: require('../assets/icons/cartGreenCircle/cartGreenCircle.png'),
  arrowDown: require('../assets/icons/arrowDown/arrowDown.png'),
  arrowRight: require('../assets/icons/catArrowRight/catArrowRight.png'),
  chatPointerLeft: require('../assets/icons/chatPointerLeft/chatPointerLeft.png'),
  chatPointerRight: require('../assets/icons/chatPointerRight/chatPointerRight.png'),
  plus: require('../assets/icons/plus/plus.png'),
  plusWhite: require('../assets/icons/plusWhite/plusWhite.png'),
  chatDelivery: require('../assets/icons/chatDelivery/chatDelivery.png'),
  callDelivery: require('../assets/icons/callDelivery/callDelivery.png'),
  cross: require('../assets/icons/cross/cross.png'),
  threeDots: require('../assets/icons/threeDots/threeDots.png'),
  send: require('../assets/icons/send/send.png'),
  crossGray: require('../assets/icons/cancelGray/cartItemcancel.png'),
  selected: require('../assets/icons/selected/selected.png'),
  inc: require('../assets/icons/inc/inc.png'),
  dec: require('../assets/icons/dec/dec.png'),
  search: require('../assets/icons/search/search.png'),
  apple: require('../assets/icons/apple/apple.png'),
  check2: require('../assets/icons/check2/check2.png'),
  uncheck2: require('../assets/icons/uncheck2/uncheck2.png'),
  facebook: require('../assets/icons/facebook/facebook.png'),
  google: require('../assets/icons/google/google.png'),
  favoriteSelected: require('../assets/icons/favoriteSelected/favoriteSelected.png'),
  favoriteUnselected: require('../assets/icons/favoriteUnselected/favoriteUnselected.png'),
  forwardArrow: require('../assets/icons/forwardArrow/forwardArrow.png'),
  heart: require('../assets/icons/heart/heart.png'),
  moreObaqueBG: require('../assets/icons/moreObaqueBG/moreObaqueBG.png'),
  more: require('../assets/icons/more/more.png'),
  chat: require('../assets/icons/chat/chat.png'),
  message: require('../assets/icons/message/message.png'),
  call: require('../assets/icons/call/call.png'),
  sliderThumb: require('../assets/icons/sliderThumb/sliderThumb.png'),
  HelpWanted: require('../assets/icons/HelpWanted/HelpWanted.png'),
  MoreCategories: require('../assets/icons/MoreCategories/MoreCategories.png'),
  add: require('../assets/icons/add/add.png'),
  remove: require('../assets/icons/remove/remove.png'),
  selectedImage: require('../assets/icons/selectedImage/selectedImage.png'),
  unselectedImage: require('../assets/icons/unselectedImage/unselectedImage.png'),
  selectedCircle: require('../assets/icons/selectedCircle/selectedCircle.png'),
  unselectedCircle: require('../assets/icons/unselectedCircle/unselectedCircle.png'),
  editOverlay: require('../assets/icons/editOverlay/editOverlay.png'),
  successful: require('../assets/icons/successful/successful.png'),
  ads: require('../assets/icons/announcement/announcement.png'),
  star: require('../assets/icons/star/star.png'),
  topicsImage: require('../assets/icons/topicsImage/topicsImage.png'),
  writeReview: require('../assets/icons/writeReview/writeReview.png'),
  starFilled: require('../assets/icons/starFilled/starFilled.png'),
  starHalfFilled: require('../assets/icons/starHalfFilled/starHalfFilled.png'),
  starUnfilled: require('../assets/icons/starUnfilled/starUnfilled.png'),
  subtract: require('../assets/icons/subtract/subtract.png'),
  addition: require('../assets/icons/addition/addition.png'),
  bringer: require('../assets/icons/bringer/bringer.png'),
  chatBubble: require('../assets/icons/chatBubble/chatBubble.png'),
  location2: require('../assets/icons/location2/location2.png'),
  phone: require('../assets/icons/phone/phone.png'),
  website: require('../assets/icons/website/website.png'),
  clock: require('../assets/icons/clock/clock.png'),
  star2: require('../assets/icons/star2/star2.png'),
  calendarIcon: require('../assets/icons/calendarIcon/calendarIcon.png'),
  video: require('../assets/icons/video/video.png'),
  callBlack: require('../assets/icons/callBlack/callBlack.png'),
  calendarLeft: require('../assets/icons/calendarLeft/calendarLeft.png'),
  calendarRight: require('../assets/icons/calendarRight/calendarRight.png'),
  list: require('../assets/icons/list/list.png'),
  calendar: require('../assets/icons/calendar/calendar.png'),
  mute: require('../assets/icons/mute/mute.png'),
  speaker: require('../assets/icons/speaker/speaker.png'),
  hangUp: require('../assets/icons/hangUp/hangUp.png'),
  callUser: require('../assets/icons/callUser/callUser.png'),
  attachment: require('../assets/icons/attachment/attachment.png'),
  drawerLeft: require('../assets/icons/drawerLeft/drawerLeft.png'),
  drawerRight: require('../assets/icons/drawerRight/drawerRight.png'),
};
const buttons = {};
const tabs = {
  Classified: require('../assets/icons/tabs/Classified/Classified.png'),
  Buying: require('../assets/icons/tabs/Buying/Buying.png'),
  Community: require('../assets/icons/tabs/Community/Community.png'),
  Food: require('../assets/icons/tabs/Food/Food.png'),
  Delivery: require('../assets/icons/tabs/Delivery/Delivery.png'),
  Delivery2: require('../assets/icons/tabs/Delivery/Delivery.png'),
  Service: require('../assets/icons/tabs/Services/Services.png'),
};

const drawer = {
  classified: require('../assets/icons/drawer/classified/classified.png'),
  orders: require('../assets/icons/drawer/orders/orders.png'),
  deliveries: require('../assets/icons/drawer/deliveries/deliveries.png'),
  calendar: require('../assets/icons/drawer/calendar/calendar.png'),
  favorite: require('../assets/icons/drawer/favorite/favorite.png'),
  wallet: require('../assets/icons/drawer/wallet/wallet.png'),
  advertising: require('../assets/icons/drawer/advertising/advertising.png'),
  addresses: require('../assets/icons/drawer/addresses/addresses.png'),
  messages: require('../assets/icons/drawer/messages/messages.png'),
  service: require('../assets/icons/drawer/service/service.png'),
  settings: require('../assets/icons/drawer/settings/settings.png'),
};

// images
const images = {
  logo: require('../assets/images/logo/logo.png'),
  directionArrow: require('../assets/images/directionArrow/directionArrow.png'),
  emptyPhoto: require('../assets/icons/emptyphoto/emptyphoto.png'),
  emptyCard: require('../assets/icons/emptyCard/emptyCard.png'),
  advertiseEmpty: require('../assets/icons/advertiseEmpty/advertiseEmpty.png'),
  inviteFriend: require('../assets/images/inviteFriend/inviteFriend.png'),
  dummyUser: require('../assets/images/dummyUser/dummyUser.png'),
  moreCategories: require('../assets/images/moreCategories/moreCategories.png'),
  unSelectedBordered: require('../assets/images/unSelectedBordered/unSelectedBordered.png'),
  selectedBordered: require('../assets/images/selectedBordered/selectedBordered.png'),
  guestProfile: require('../assets/images/guestProfile/guestProfile.png'),
  alert: require('../assets/images/alert/alert.png'),
};

// vechile images
const vehicles = {
  bike: require('../assets/vehicles/bike/bike.png'),
  truck: require('../assets/vehicles/truck/truck.png'),
  van: require('../assets/vehicles/van/van.png'),
  miniCarge: require('../assets/vehicles/miniCarge/miniCarge.png'),
};

const emptyImages = {
  messages: require('../assets/icons/messages/messages.png'),
  calendarEmpty: require('../assets/icons/calendarEmpty/calendarEmpty.png'),
  serviceEmptyPending: require('../assets/icons/serviceEmptyPending/serviceEmptyPending.png'),
  deliveriesEmpty: require('../assets/icons/deliveriesEmpty/deliveriesEmpty.png'),
  orderCompletedEmpty: require('../assets/icons/orderCompletedEmpty/orderCompletedEmpty.png'),
  ratingEmpty: require('../assets/icons/ratingEmpty/ratingEmpty.png'),
  notificationEmpty: require('../assets/icons/notificationEmpty/notificationEmpty.png'),
  myCartEmpty: require('../assets/icons/myCartEmpty/myCartEmpty.png'),
  classifiedEmpty: require('../assets/icons/classifiedEmpty/classifiedEmpty.png'),
  buyingEmpty: require('../assets/icons/buyingEmpty/buyingEmpty.png'),
  foodEmpty: require('../assets/icons/foodEmpty/foodEmpty.png'),
  emptyFoodOrder: require('../assets/icons/emptyFoodOrder/emptyFoodOrder.png'),
};

const toolbar = {
  justifyRight: require('../assets/icons/toolbar/RightAlign/RightAlign.png'),
  justifyLeft: require('../assets/icons/toolbar/LeftAlign/LeftAlign.png'),
  justifyCenter: require('../assets/icons/toolbar/CenterAlign/CenterAlign.png'),
  bold: require('../assets/icons/toolbar/bold/bold.png'),
  italic: require('../assets/icons/toolbar/italic/italic.png'),
  fontFamily: require('../assets/icons/toolbar/fontFamily/fontFamily.png'),
};

const cards = {
  visa: require('../assets/images/cards/visaDummy/visaDummy.png'),
  masterCard: require('../assets/images/cards/masterCard/masterCard.png'),
  jcb: require('../assets/images/cards/jcb/jcb.png'),
  dummyCard: require('../assets/images/cards/dummyCard/dummyCard.png'),
  discover: require('../assets/images/cards/discover/discover.png'),
  dinersClub: require('../assets/images/cards/dinersClub/dinersClub.png'),
  americanExpress: require('../assets/images/cards/americanExpress/americanExpress.png'),
  bizadwallet: require('../assets/icons/bizadwallet/bizadwallet.png'),
};

const dummyImages = {
  cartItem1: require('../assets/dummyImages/cart/cartItem1/cartItem1.png'),
  cartItem2: require('../assets/dummyImages/cart/cartItem2/cartItem2.png'),
  cartItem3: require('../assets/dummyImages/cart/cartItem3/cartItem3.png'),
  cartItem4: require('../assets/dummyImages/cart/cartItem4/cartItem4.png'),
  cartItem5: require('../assets/dummyImages/cart/cartItem5/cartItem5.jpg'),
  foodItem1: require('../assets/dummyImages/food/foodItem1/foodItem1.png'),
  foodItem2: require('../assets/dummyImages/food/foodItem2/foodItem2.png'),
  foodItem3: require('../assets/dummyImages/food/foodItem3/foodItem3.png'),
  camera: require('../assets/dummyImages/camera/camera.jpg'),
  camera2: require('../assets/dummyImages/camera2/camera2.png'),
  burger1small: require('../assets/dummyImages/burgers/burger1small/burger1small.png'),
  burger2small: require('../assets/dummyImages/burgers/burger2small/burger2small.png'),
  carimg1: require('../assets/dummyImages/cars/carimg1/carimg1.png'),
  carimg2: require('../assets/dummyImages/cars/carimg2/carimg2.png'),
  carimg3: require('../assets/dummyImages/cars/carimg3/carimg3.png'),
  carimg4: require('../assets/dummyImages/cars/carimg4/carimg4.png'),
  carimg5: require('../assets/dummyImages/cars/carimg5/carimg5.png'),
  carimg6: require('../assets/dummyImages/cars/carimg6/carimg6.png'),
  carimg7: require('../assets/dummyImages/cars/carimg7/carimg7.jpeg'),
  carimg8: require('../assets/dummyImages/cars/carimg8/carimg8.jpg'),
  carimg9: require('../assets/dummyImages/cars/carimg9/carimg9.jpg'),
  deliveryImage1: require('../assets/dummyImages/deliveryImage1/deliveryImage1.png'),
  deliveryImage2: require('../assets/dummyImages/deliveryImage2/deliveryImage2.png'),
  vehiclesLarge: require('../assets/dummyImages/categoriesLarge/vehiclesLarge/vehiclesLarge.png'),
  mobileLarge: require('../assets/dummyImages/categoriesLarge/mobileLarge/mobileLarge.png'),
  fashionLarge: require('../assets/dummyImages/categoriesLarge/fashionLarge/fashionLarge.png'),
  electronicsLarge: require('../assets/dummyImages/categoriesLarge/electronicsLarge/electronicsLarge.png'),
  moreCategories: require('../assets/dummyImages/categoriesLarge/moreCategories/moreCategories.png'),
  helpWanted: require('../assets/dummyImages/categoriesLarge/helpWanted/helpWanted.png'),
  vehicleGrid: require('../assets/dummyImages/vehicleGrid/vehicleGrid.png'),
  vehicles: require('../assets/dummyImages/categories/vehicles/vehicles.png'),
  apparelGrid: require('../assets/dummyImages/categories/apparel/apparel.png'),
  mobileGrid: require('../assets/dummyImages/mobileLarge/mobileLarge.png'),
  fashionGrid: require('../assets/dummyImages/fashionLarge/fashionLarge.png'),
  electronicsGrid: require('../assets/dummyImages/electronicLarge/electronicLarge.png'),
  mobiles: require('../assets/dummyImages/categories/Mobiles/Mobiles.png'),
  fashion: require('../assets/dummyImages/categories/Fashion/Fashion.png'),
  electronics: require('../assets/dummyImages/categories/Electronics/Electronics.png'),
  kids: require('../assets/dummyImages/categories/kids/kids.png'),
  dummyCarLarge: require('../assets/dummyImages/dummyCarLarge/dummyCarLarge.png'),
  dummyCurrentLocation: require('../assets/dummyImages/dummyCurrentLocation/dummyCurrentLocation.png'),
  dummyProfilePic: require('../assets/dummyImages/dummyProfilePic/dummyProfilePic.png'),
  dummyMap: require('../assets/dummyImages/dummyMap/dummyMap.png'),
  dummyUserImage: require('../assets/dummyImages/dummyUserImage/dummyUserImage.png'),
  dummyItem: require('../assets/dummyImages/dummyItem/dummyItem.png'),
  visaDummy: require('../assets/dummyImages/visaDummy/visaDummy.png'),
  house: require('../assets/dummyImages/house/house.jpeg'),
  service1: require('../assets/dummyImages/categories/service1/service1.png'),
  service2: require('../assets/dummyImages/categories/service2/service2.png'),
  service3: require('../assets/dummyImages/categories/service3/service3.png'),
  service4: require('../assets/dummyImages/categories/service4/service4.png'),
  service5: require('../assets/dummyImages/service1/service1.png'),
  service6: require('../assets/dummyImages/service2/service2.png'),
  topicItemLarge: require('../assets/dummyImages/topicItemLarge/topicItemLarge.png'),
  businesslarge: require('../assets/dummyImages/categories/topicsLarge/businesslarge/businesslarge.png'),
  healthLarge: require('../assets/dummyImages/categories/topicsLarge/healthLarge/healthLarge.png'),
  socialLarge: require('../assets/dummyImages/categories/topicsLarge/socialLarge/socialLarge.png'),
  educationLarge: require('../assets/dummyImages/categories/topicsLarge/educationLarge/educationLarge.png'),
  environment: require('../assets/dummyImages/categories/topicsSmall/environment/environment.png'),
  general: require('../assets/dummyImages/categories/topicsSmall/general/general.png'),
  business: require('../assets/dummyImages/categories/topicsSmall/business/business.png'),
  health: require('../assets/dummyImages/categories/topicsSmall/health/health.png'),
  social: require('../assets/dummyImages/categories/topicsSmall/social/social.png'),
  education: require('../assets/dummyImages/categories/topicsSmall/education/education.png'),
  topic1: require('../assets/dummyImages/topics/topic1/topic1.png'),
  topic2: require('../assets/dummyImages/topics/topic2/topic2.png'),
  topic3: require('../assets/dummyImages/topics/topic3/topic3.png'),
  topic4: require('../assets/dummyImages/topics/topic4/topic4.png'),
  topicSlider: require('../assets/dummyImages/topicSlider/topicSlider.png'),
  serviceCat2: require('../assets/dummyImages/categories/serviceCat2/serviceCat2.png'),
  serviceCat3: require('../assets/dummyImages/categories/serviceCat3/serviceCat3.png'),
  serviceCat4: require('../assets/dummyImages/categories/serviceCat4/serviceCat4.png'),
  serviceCat5: require('../assets/dummyImages/categories/serviceCat5/serviceCat5.png'),
  serviceCat6: require('../assets/dummyImages/categories/serviceCat6/serviceCat6.png'),
  serviceCat7: require('../assets/dummyImages/categories/serviceCat7/serviceCat7.png'),
  serviceItem1: require('../assets/dummyImages/categories/serviceItem1/serviceItem1.png'),
  serviceItem2: require('../assets/dummyImages/categories/serviceItem2/serviceItem2.png'),
  serviceItem3: require('../assets/dummyImages/categories/serviceItem3/serviceItem3.png'),
  serviceItem4: require('../assets/dummyImages/categories/serviceItem4/serviceItem4.png'),
  user1: require('../assets/dummyImages/user1/user1.png'),
  user2: require('../assets/dummyImages/user2/user2.png'),
};

export default {
  drawer,
  icons,
  buttons,
  images,
  vehicles,
  dummyImages,
  emptyImages,
  tabs,
  toolbar,
  cards,
};
