export const whiteList = [
  'auth',
  'drawerPreference',
  'location',
  'searchKeyword',
  'searchHistory',
  'buyingCart',
  'radius',
  'orders',
  'chatRooms',
  'pushToken',
  'payment',
  'appleCredentials',
  'foodCart',
  'userRoles',
];
